cluster_label: "test_cluster"
region: "us-east-1"
provider: "aws"
availability_zone: "us-east-1c"

private_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa"
public_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa.pub"
public_key_name: "vanderlei@RIVET-LABS-MAC-HGMW6NW46J.local"

master_ami: "ami-053a3b7c158c56eb5"
master_instance_type: "t2.micro"
master_rbs_size: 100
master_rbs_type: "io2"
master_rbs_iops: 5000

worker_count: 3
worker_ami: "ami-053a3b7c158c56eb5"
worker_instance_type: "t2.micro"
worker_rbs_size: 100
worker_rbs_type: "io2"
worker_rbs_iops: 5000

use_efa: "false"
use_fsx: "false"
use_nfs: "true"
use_spot: "false"
spot_maximum_rate: 5

experiment_tag: "development-mac"
instance_username: "ec2-user"
