services:
  postgres:
    image: postgres:16.2-bookworm
    container_name: hpcac-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: postgres
    volumes:
      - ./workspace/postgres:/var/lib/postgresql

  minio:
    image: minio/minio:latest
    container_name: hpcac-minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./workspace/minio/data:/data/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: minio server /data/minio --console-address ":9090"
