cluster_label: "test_cluster"
provider: "aws"

private_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa"
public_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa.pub"
public_key_name: "vanderlei@RIVET-LABS-MAC-HGMW6NW46J.local"

aws_secret_key: "xxxx"
aws_access_key: "xxxx"

master_ami: "ami-06595df5f34c718e5"
master_instance_type: "c5n.9xlarge"
master_rbs_size: 50
master_rbs_type: "io2"
master_rbs_iops: 2500

worker_count: 3
worker_ami: "ami-06595df5f34c718e5"
worker_instance_type: "c5n.9xlarge"
worker_rbs_size: 50
worker_rbs_type: "io2"
worker_rbs_iops: 2500

use_spot: "true"
spot_maximum_rate: 0.5

experiment_tag: "cost-allocation-tracking-tag"
instance_username: "ec2-user"
